import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
<<<<<<< Updated upstream
import "rsuite/dist/rsuite.min.css";
=======

>>>>>>> Stashed changes
import "./globals.css";
import Providers from "./providers";

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-work-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${workSans.variable} h-full antialiased`}>
      <body>
        <Providers>
          {children}

          <ToastContainer
            position="top-center"
            autoClose={3000}
            hideProgressBar={false}
            closeOnClick
            pauseOnHover
            draggable
            theme="light"
          />
        </Providers>
      </body>
    </html>
  );
}
